### PR TITLE
Add ability to build json for nested comments 

### PR DESCRIPTION
**Pull request by victir**
using gem 'active_model_serializers'

### CODE REVIEW

**Comment by jrothrock** [comment]
Wowa, I really appreciate this man. Definitely a lot easier to use than my way haha

**Comment by jrothrock** [comment]
Superr odd question, but you don't happen to know a Danish by any chance?

**Comment by victir** [comment]
@jrothrock Sorry I do not know Danish, but I speak english, russian and ukrainian :)

**Comment by jrothrock** [comment]
Oh he's a person haha, but that's honestly super impressive

**Comment by jrothrock** [comment]
Also, if you don't mind me asking. How did you find this repo?

**Comment by victir** [comment]
@jrothrock https://www.upwork.com/jobs/_~01d0ad70b9f568deb4/

**Pull request merged**
